from dataclasses import dataclass

@dataclass(frozen=True)
class AuthContext:
    """Trusted identity passed by the runtime, never generated by the LLM."""
    employee_id: str
    tenant_id: str
    roles: tuple[str, ...] = ("employee",)
